name: hydrated_bloc_weather
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^6.0.5
  equatable: ^1.2.5
  json_annotation: ^3.0.1
  hydrated_bloc: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  json_serializable: ^3.4.1

flutter:
  uses-material-design: true

